name = "Kiera"
license = "MIT"
licenselink = "https://github.com/avianto/hugo-kiera/blob/master/LICENSE.md"
description = ""
homepage = "http://github.com/avianto/hugo-kiera"
tags = []
features = []
min_version = "0.30.2"

[author]
  name = "b. avianto"
  homepage = "http://avianto.com/"
